device: /dev/ttyACM0
frame_id: gps
uart1:
  baudrate: 38400
config_on_startup: false

inf:
  all: true

publish:
  esf:
    alg: true
    meas: true
    status: true
  nav:
    att: true
    pvt: true
    status: true

debug: 0